<?php
/**
 * @var  $block  Mobile
 */

use Codilar\Mobile\Block\Add\Mobile;



?>





<form method="post"  action="<?=$block->getUrl(route: 'mobile/add/save')?> ">

    <div>
          <label><?= "Mobile Name" ?></label>
           <input type="text" name="name" id="name">
    </div>

    <div>
        <label><?= "Mobile Price"?> </label>
        <input type="text" name="price" id="price">
    </div>

    <div>
        <label><?= "Mobile Company"?> </label>
        <input type="text" name="company" id="company">
    </div>


    <div>
           <button type="submit">Submit</button>
    </div>


</form>

