<?php
/**
 * @var $block Display
 */
$workers = $block->getAllUsers();

use Codilar\User\Block\Display;

?>

<style>
    :root {
        --placeholder-image: linear-gradient(to right, rgba(0, 0, 0, .08) 0, rgba(0, 0, 0, .15) 15%, rgba(0, 0, 0, .08) 30%);
        --placeholder-size: 1200px 100%;
        --placeholder-animation: placeholderAnimation 2s linear infinite;
        --primary-divider-color: #f0f0f0;
    }
    }
    .loader {

        animation: var(--placeholder-animation);
        background-image: var(--placeholder-image);
        background-size: var(--placeholder-size);
        height: var(--option-size);
        width: var(--option-size);
    }

    .loader {
        min-height: 100%;
        min-width: 200px;
        animation: var(--placeholder-animation);
        background-image: var(--placeholder-image);
        background-size: var(--placeholder-size);
        height: var(--option-size);
        width: var(--option-size);
    }
</style>

<table border="1" id="user" class="loader">

</table>

<hr/>
<form action="<?=$block->getPostUrl()?>" method="POST">
    <fieldset>
        <div>
            <label for="name">Name : </label>
            <input type="text" name="name"/>
        </div>
        <div>
            <label for="dob">Date of Birth : </label>
            <input type="date" name="dob"/>
        </div>
        <div>
            <label for="email">Email : </label>
            <input type="varchar" name="email"/>
        </div>
        <div>
            <label for="address">Address : </label>
            <input type="varchar" name="address"/>
        </div>
        <div>
            <label for="image">Upload Your Image : </label>
            <input type="file" name="image"/>
        </div>
        <input type="submit" name="submit" value="submit"/>
    </fieldset>
</form>

<script>
    function getUser() {
        fetch("<?=$block->getUrl('user/details/get')?>").then(response => response.json().then(
            jsonResponse =>{
                let tableData = JSON.parse(jsonResponse);
                const tableDOM = document.getElementById('user');
                tableDOM.innerHTML = "<tr><th>ID</th><th>Name</th><th>Date of Birth</th><th>Email</th><th>Address</th><th>Image</th></tr>";
                tableDOM.className="";
                for(i=0;i<tableData.length;i++) {
                    let tr = document.createElement('tr');
                    tr.innerHTML = '<th>'+tableData[i].id+'</th><th>'+tableData[i].name+'</th><th>'+tableData[i].dob+'</th><th>'+tableData[i].email+'</th><th>'+tableData[i].address+'</th><th>'+tableData[i].image+'</th>';
                    tableDOM.appendChild(tr);
                }
            }
        ))
    }
    getUser();
</script>
