<?php
/**
 * @var $block Employee
 **/
use Codilar\Employee\Block\Add\Employee;
?>
<form method="post" action="">
    <div>
          <label><?= "Employee Name" ?></label>
           <input type="text" name="name" id="name">
    </div>

    <div>
        <label><?= "Employee Companyname"?> </label>
        <input type="text" name="companyname" id="companyname">
    </div>


    <div>
           <button type="submit">Submit</button>
    </div>
</form>