<?php
use Codilar\OutStock\Block\Config;

/**
 * @var $block Config
 */
?>

<?php if($block->isModuleEnabled()):?>





    <div>
        <a href="#" id="click-me">Notify me!</a>
    </div>

    <div id="popup-modal" style="display:none;">
        <h4>Subscribe Back-In-Stock Alerts now! Register your email address to be the first to know when our
            product comes back. Do not miss your chance! </h4>
        <form action="<?=$block->getPostUrl()?>" method="post">
            <label for="name">Name:</label>
            <input type="text" id="name" name="name"><br><br>
            <label for="phone">Phone:</label>
            <input type="text" id="phone" name="phone"><br><br>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email"><br><br>
            <input type="submit" name="Submit" >
        </form>
        <h4>Kindly notice that the back-in-stock email will be delivered only one time, and your email address
            will not be shared or published with anyone else.</h4>
    </div>

    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function (
                $,
                modal
            ) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Grab your chance when this product back in stock!',
                    buttons: [{
                        text: $.mage.__('Close'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                var popup = modal(options, $('#popup-modal'));
                $("#click-me").on('click',function(){
                    $("#popup-modal").modal("openModal");
                });

            }
        );

    </script>
<?php endif?>

